#!/usr/bin/env bash
# scripts/gen_hashes.sh — regenerate yapsnap's model checksum manifest
# and (optionally) the pip requirements lock file.
#
# Usage:
#   ./scripts/gen_hashes.sh              # regenerate everything
#   ./scripts/gen_hashes.sh --models     # model checksums only
#   ./scripts/gen_hashes.sh --lock       # requirements lock only
#
# The model manifest covers every file yapsnap may auto-download:
#   - The 4 ASR model files (encoder.onnx, decoder.onnx, joiner.onnx,
#     tokens.txt) for each language repo in LANG_MODELS.
#   - Diarization model files listed in DIARIZATION_FILES below.
#
# The script downloads each file to a temp directory, hashes it, and
# writes yapsnap/model_checksums.sha256 in standard sha256sum format.
# Files already in the temp dir are reused (cache-friendly for reruns).
#
# Requirements: curl, sha256sum (or shasum on macOS).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
MANIFEST="$REPO_ROOT/yapsnap/model_checksums.sha256"

HF_BASE="https://huggingface.co"
MODEL_FILES=(encoder.onnx decoder.onnx joiner.onnx tokens.txt)

# All language repos — must match LANG_MODELS in yapsnap/__init__.py.
LANG_REPOS=(
    "kouhxp/sherpa-onnx-streaming-zipformer-de-kroko"
    "kouhxp/sherpa-onnx-streaming-zipformer-en-kroko"
    "kouhxp/sherpa-onnx-streaming-zipformer-es-kroko"
    "kouhxp/sherpa-onnx-streaming-zipformer-fr-kroko"
    "kouhxp/sherpa-onnx-streaming-zipformer-it-kroko"
    "kouhxp/sherpa-onnx-streaming-zipformer-iw-kroko"
    "kouhxp/sherpa-onnx-streaming-zipformer-nl-kroko"
    "kouhxp/sherpa-onnx-streaming-zipformer-pt-kroko"
    "kouhxp/sherpa-onnx-streaming-zipformer-sv-kroko"
    "kouhxp/sherpa-onnx-streaming-zipformer-tr-kroko"
)

# Diarization models — add entries here when diarize.py auto-downloads
# files that need verification.  Format: "repo  filename"
# These are stored as bare filenames in the manifest (no repo prefix).
DIARIZATION_FILES=()

# ---------------------------------------------------------------------------

SHA_CMD=""
if command -v sha256sum &>/dev/null; then
    SHA_CMD="sha256sum"
elif command -v shasum &>/dev/null; then
    SHA_CMD="shasum -a 256"
else
    echo "error: neither sha256sum nor shasum found" >&2
    exit 1
fi

do_models=true
do_lock=true

for arg in "$@"; do
    case "$arg" in
        --models) do_lock=false ;;
        --lock)   do_models=false ;;
        -h|--help)
            echo "Usage: $0 [--models] [--lock]"
            echo "  --models   regenerate model checksums only"
            echo "  --lock     regenerate requirements lock only"
            echo "  (no args)  regenerate both"
            exit 0
            ;;
        *)
            echo "unknown argument: $arg" >&2
            exit 1
            ;;
    esac
done

# ---------------------------------------------------------------------------
# Model checksums
# ---------------------------------------------------------------------------

if $do_models; then
    CACHE="${YAPSNAP_HASH_CACHE:-${TMPDIR:-/tmp}/yapsnap-gen-hashes}"
    mkdir -p "$CACHE"

    echo "==> Generating model checksums"
    echo "    cache dir: $CACHE"
    echo ""

    # Start the manifest with a header.
    cat > "$MANIFEST" <<'EOF'
# yapsnap model checksum manifest — SHA-256
#
# Auto-generated by scripts/gen_hashes.sh — do not edit by hand.
# Format: <sha256-hex>  <repo/filename>
#
# Language-model entries are keyed by repo/filename so each language's
# encoder.onnx etc. gets a distinct digest.  Diarization entries use
# bare filenames (no repo prefix).
#
# yapsnap/_download() verifies every auto-downloaded file against this
# manifest under a hard-fail policy.
EOF

    for repo in "${LANG_REPOS[@]}"; do
        repo_dir="$CACHE/${repo//\//__}"
        mkdir -p "$repo_dir"

        echo "--- $repo ---"

        for fname in "${MODEL_FILES[@]}"; do
            dest="$repo_dir/$fname"
            url="$HF_BASE/$repo/resolve/main/$fname"

            if [[ -f "$dest" ]]; then
                echo "  [cached] $fname"
            else
                echo "  [fetch]  $fname"
                curl -fSL --retry 3 --retry-delay 5 \
                     -H "User-Agent: yapsnap/gen_hashes" \
                     -o "$dest.part" "$url"
                mv "$dest.part" "$dest"
            fi

            digest=$($SHA_CMD "$dest" | awk '{print $1}')
            echo "$digest  $repo/$fname" >> "$MANIFEST"
        done
        echo ""
    done

    # Diarization models (bare-filename entries).
    for entry in "${DIARIZATION_FILES[@]}"; do
        repo=$(echo "$entry" | awk '{print $1}')
        fname=$(echo "$entry" | awk '{print $2}')
        repo_dir="$CACHE/${repo//\//__}"
        mkdir -p "$repo_dir"
        dest="$repo_dir/$fname"
        url="$HF_BASE/$repo/resolve/main/$fname"

        if [[ -f "$dest" ]]; then
            echo "  [cached] $fname ($repo)"
        else
            echo "  [fetch]  $fname ($repo)"
            curl -fSL --retry 3 --retry-delay 5 \
                 -H "User-Agent: yapsnap/gen_hashes" \
                 -o "$dest.part" "$url"
            mv "$dest.part" "$dest"
        fi

        digest=$($SHA_CMD "$dest" | awk '{print $1}')
        echo "$digest  $fname" >> "$MANIFEST"
    done

    echo "==> Wrote $MANIFEST"
    wc -l "$MANIFEST"
    echo ""
fi

# ---------------------------------------------------------------------------
# Requirements lock
# ---------------------------------------------------------------------------

if $do_lock; then
    echo "==> Regenerating requirements-lock.txt"
    LOCKFILE="$REPO_ROOT/requirements-lock.txt"

    if command -v pip-compile &>/dev/null; then
        pip-compile --generate-hashes \
            --output-file "$LOCKFILE" \
            "$REPO_ROOT/pyproject.toml"
        echo "==> Wrote $LOCKFILE"
    else
        echo "  pip-compile not found; install pip-tools and rerun, or regenerate manually:"
        echo "    pip-compile --generate-hashes --output-file requirements-lock.txt pyproject.toml"
    fi
    echo ""
fi

echo "Done."
